// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace School_Project_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260601000721_Add Homework Controller")]
    partial class AddHomeworkController
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("School_Project_API.Entities.AccessCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("AccessCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpirationDate = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNo = "ABCAW"
                        },
                        new
                        {
                            Id = 2,
                            ExpirationDate = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNo = "ABCAX"
                        },
                        new
                        {
                            Id = 3,
                            ExpirationDate = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNo = "ABCBW"
                        },
                        new
                        {
                            Id = 4,
                            ExpirationDate = new DateTime(2025, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNo = "ABCBX"
                        },
                        new
                        {
                            Id = 5,
                            ExpirationDate = new DateTime(2025, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNo = "ABCCA"
                        },
                        new
                        {
                            Id = 6,
                            ExpirationDate = new DateTime(2025, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNo = "ABCCX"
                        },
                        new
                        {
                            Id = 7,
                            ExpirationDate = new DateTime(2025, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNo = "ABCDW"
                        },
                        new
                        {
                            Id = 8,
                            ExpirationDate = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNo = "ABCDX"
                        },
                        new
                        {
                            Id = 9,
                            ExpirationDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNo = "ABCDE"
                        },
                        new
                        {
                            Id = 10,
                            ExpirationDate = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNo = "ABCDF"
                        },
                        new
                        {
                            Id = 11,
                            ExpirationDate = new DateTime(2025, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNo = "ABCDG"
                        },
                        new
                        {
                            Id = 12,
                            ExpirationDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNo = "ABCDH"
                        },
                        new
                        {
                            Id = 13,
                            ExpirationDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNo = "ABCDI"
                        });
                });

            modelBuilder.Entity("School_Project_API.Entities.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId", "Date")
                        .IsUnique()
                        .HasFilter("[StudentId] IS NOT NULL AND [Date] IS NOT NULL");

                    b.ToTable("Attendances", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "On time",
                            Status = 1,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Sick",
                            Status = 2,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Traffic",
                            Status = 3,
                            StudentId = 3
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Excellent",
                            Status = 1,
                            StudentId = 4
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Medical excuse",
                            Status = 4,
                            StudentId = 5
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "On time",
                            Status = 1,
                            StudentId = 6
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Travel",
                            Status = 2,
                            StudentId = 7
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Good",
                            Status = 1,
                            StudentId = 8
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Late bus",
                            Status = 3,
                            StudentId = 9
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Participated",
                            Status = 1,
                            StudentId = 10
                        });
                });

            modelBuilder.Entity("School_Project_API.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasDefaultValue("No Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Classes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            Description = "Backend",
                            Name = "Class A",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 25,
                            Description = "Frontend",
                            Name = "Class B",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 20,
                            Description = "HR",
                            Name = "Class C",
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 35,
                            Description = "Finance",
                            Name = "Class D",
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 40,
                            Description = "Marketing",
                            Name = "Class E",
                            TeacherId = 5
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 28,
                            Description = "Sales",
                            Name = "Class F",
                            TeacherId = 6
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 32,
                            Description = "Operations",
                            Name = "Class G",
                            TeacherId = 7
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 18,
                            Description = "Security",
                            Name = "Class H",
                            TeacherId = 8
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 22,
                            Description = "AI",
                            Name = "Class I",
                            TeacherId = 9
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 26,
                            Description = "Networking",
                            Name = "Class J",
                            TeacherId = 10
                        });
                });

            modelBuilder.Entity("School_Project_API.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "/images/asp.png",
                            Name = "ASP.NET Core",
                            Price = 100m
                        },
                        new
                        {
                            Id = 2,
                            ImagePath = "/images/react.png",
                            Name = "React.js",
                            Price = 120m
                        },
                        new
                        {
                            Id = 3,
                            ImagePath = "/images/sql.png",
                            Name = "SQL Server",
                            Price = 80m
                        },
                        new
                        {
                            Id = 4,
                            ImagePath = "/images/docker.png",
                            Name = "Docker",
                            Price = 90m
                        },
                        new
                        {
                            Id = 5,
                            ImagePath = "/images/azure.png",
                            Name = "Azure",
                            Price = 110m
                        },
                        new
                        {
                            Id = 6,
                            ImagePath = "/images/python.png",
                            Name = "Python",
                            Price = 95m
                        },
                        new
                        {
                            Id = 7,
                            ImagePath = "/images/security.png",
                            Name = "Cyber Security",
                            Price = 130m
                        },
                        new
                        {
                            Id = 8,
                            ImagePath = "/images/ml.png",
                            Name = "Machine Learning",
                            Price = 150m
                        },
                        new
                        {
                            Id = 9,
                            ImagePath = "/images/network.png",
                            Name = "Networking",
                            Price = 85m
                        },
                        new
                        {
                            Id = 10,
                            ImagePath = "/images/algo.png",
                            Name = "Algorithms",
                            Price = 140m
                        });
                });

            modelBuilder.Entity("School_Project_API.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Operations"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Cyber Security"
                        },
                        new
                        {
                            Id = 8,
                            Name = "AI"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Networking"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Business"
                        });
                });

            modelBuilder.Entity("School_Project_API.Entities.Homework", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("DueDate");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Homeworks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Complete exercises 1 to 15 from the algebra worksheet.",
                            DueDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            SubjectId = 1,
                            TeacherId = 1,
                            Title = "Math Algebra Practice"
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 2,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Write a lab report about the plant growth experiment.",
                            DueDate = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            SubjectId = 2,
                            TeacherId = 1,
                            Title = "Science Lab Report"
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 1,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Read chapter 4 and write a one-page summary.",
                            DueDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            SubjectId = 3,
                            TeacherId = 2,
                            Title = "English Reading Summary"
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 3,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Create a timeline of key events from the lesson.",
                            DueDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            SubjectId = 4,
                            TeacherId = 2,
                            Title = "History Timeline"
                        },
                        new
                        {
                            Id = 5,
                            ClassId = 2,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Label the countries and capitals on the provided map.",
                            DueDate = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            SubjectId = 5,
                            TeacherId = 3,
                            Title = "Geography Map Activity"
                        },
                        new
                        {
                            Id = 6,
                            ClassId = 4,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Answer the questions about hardware and software.",
                            DueDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            SubjectId = 6,
                            TeacherId = 3,
                            Title = "Computer Basics Assignment"
                        },
                        new
                        {
                            Id = 7,
                            ClassId = 3,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Complete the grammar exercises from page 32.",
                            DueDate = new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            SubjectId = 7,
                            TeacherId = 4,
                            Title = "Arabic Grammar Practice"
                        },
                        new
                        {
                            Id = 8,
                            ClassId = 4,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Draw a still-life sketch using pencil shading.",
                            DueDate = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            SubjectId = 8,
                            TeacherId = 4,
                            Title = "Art Sketch Assignment"
                        },
                        new
                        {
                            Id = 9,
                            ClassId = 5,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Write a short reflection about teamwork in sports.",
                            DueDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            SubjectId = 9,
                            TeacherId = 5,
                            Title = "Physical Education Reflection"
                        },
                        new
                        {
                            Id = 10,
                            ClassId = 5,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Complete the revision worksheet before next class.",
                            DueDate = new DateTime(2026, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            SubjectId = 10,
                            TeacherId = 5,
                            Title = "Final Revision Worksheet"
                        });
                });

            modelBuilder.Entity("School_Project_API.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("CardId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .IsUnique()
                        .HasFilter("[CardId] IS NOT NULL");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Amman",
                            CardId = 1,
                            DateOfBirth = new DateTime(2003, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "m1@test.com",
                            FirstName = "Mohammad",
                            Gender = "Male",
                            LastName = "Shiplak",
                            Phone = "111"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Irbid",
                            CardId = 2,
                            DateOfBirth = new DateTime(2002, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "m2@test.com",
                            FirstName = "Ahmad",
                            Gender = "Male",
                            LastName = "Ali",
                            Phone = "222"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Zarqa",
                            CardId = 3,
                            DateOfBirth = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "m3@test.com",
                            FirstName = "Sara",
                            Gender = "Female",
                            LastName = "Khaled",
                            Phone = "333"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Aqaba",
                            CardId = 4,
                            DateOfBirth = new DateTime(2000, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "m4@test.com",
                            FirstName = "Lina",
                            Gender = "Female",
                            LastName = "Hasan",
                            Phone = "444"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Madaba",
                            CardId = 5,
                            DateOfBirth = new DateTime(1999, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 5,
                            Email = "m5@test.com",
                            FirstName = "Omar",
                            Gender = "Male",
                            LastName = "Salem",
                            Phone = "555"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Salt",
                            CardId = 6,
                            DateOfBirth = new DateTime(2003, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 6,
                            Email = "m6@test.com",
                            FirstName = "Rami",
                            Gender = "Male",
                            LastName = "Naser",
                            Phone = "666"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Karak",
                            CardId = 7,
                            DateOfBirth = new DateTime(2002, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 7,
                            Email = "m7@test.com",
                            FirstName = "Noor",
                            Gender = "Female",
                            LastName = "Sami",
                            Phone = "777"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Jerash",
                            CardId = 8,
                            DateOfBirth = new DateTime(2001, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 8,
                            Email = "m8@test.com",
                            FirstName = "Yousef",
                            Gender = "Male",
                            LastName = "Adel",
                            Phone = "888"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Ajloun",
                            CardId = 9,
                            DateOfBirth = new DateTime(2000, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 9,
                            Email = "m9@test.com",
                            FirstName = "Mona",
                            Gender = "Female",
                            LastName = "Ahmad",
                            Phone = "999"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Mafraq",
                            CardId = 10,
                            DateOfBirth = new DateTime(1998, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 10,
                            Email = "m10@test.com",
                            FirstName = "Khaled",
                            Gender = "Male",
                            LastName = "Jamal",
                            Phone = "1010"
                        });
                });

            modelBuilder.Entity("School_Project_API.Entities.StudentSubjects", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Grade")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("StudentId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentSubjects", (string)null);
                });

            modelBuilder.Entity("School_Project_API.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SubjectName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Price = 50m,
                            SubjectName = "C#",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            Price = 60m,
                            SubjectName = "EF Core",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 2,
                            Price = 40m,
                            SubjectName = "HTML",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            Price = 40m,
                            SubjectName = "CSS",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 3,
                            Price = 55m,
                            SubjectName = "SQL Basics",
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 4,
                            Price = 65m,
                            SubjectName = "Docker Basics",
                            TeacherId = 7
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 5,
                            Price = 75m,
                            SubjectName = "Azure Fundamentals",
                            TeacherId = 9
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 6,
                            Price = 45m,
                            SubjectName = "Python Basics",
                            TeacherId = 9
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 7,
                            Price = 90m,
                            SubjectName = "Ethical Hacking",
                            TeacherId = 8
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 10,
                            Price = 100m,
                            SubjectName = "Data Structures",
                            TeacherId = 10
                        });
                });

            modelBuilder.Entity("School_Project_API.Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Teachers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            HireDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ali Ahmad",
                            Specialization = "Backend"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            HireDate = new DateTime(2021, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sara Khaled",
                            Specialization = "Frontend"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            HireDate = new DateTime(2019, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Omar Sami",
                            Specialization = "HR"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 3,
                            HireDate = new DateTime(2022, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lina Hasan",
                            Specialization = "Finance"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 4,
                            HireDate = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ahmad Naser",
                            Specialization = "Marketing"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 5,
                            HireDate = new DateTime(2018, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Yousef Adel",
                            Specialization = "Sales"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 6,
                            HireDate = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mona Ali",
                            Specialization = "Operations"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 7,
                            HireDate = new DateTime(2021, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Khaled Jamal",
                            Specialization = "Cyber Security"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 8,
                            HireDate = new DateTime(2019, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rami Saeed",
                            Specialization = "AI"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 9,
                            HireDate = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Noor Hasan",
                            Specialization = "Networking"
                        });
                });

            modelBuilder.Entity("School_Project_API.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@gmail.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$c.4Cmj3rP.Zrpq9PD0ZZveE/aMFE504E9hxqbVVWKesvuDwElKksu",
                            Role = "Admin",
                            UserName = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "teacher1@gmail.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$BwOhy/TISJ6FY796dT0I.eN5SALsWuTs6JRp9sRtD0bpXcwEYojtS",
                            Role = "Teacher",
                            UserName = "teacher1"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "teacher2@gmail.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$AnlrDcQ1SMmjaQd9WMr8RO1/IC2g9fUdx9TOAMzorCCC7D/OcMHLa",
                            Role = "Teacher",
                            UserName = "teacher2"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "student1@gmail.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$3Q7ktMT/zai/u.w7PHB7h.2h28yrTIKaLnLDaB0kYfQqAr2ZUSevK",
                            Role = "Student",
                            UserName = "student1"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "student2@gmail.com",
                            IsActive = false,
                            PasswordHash = "$2a$11$vSO5US.IN.S5qC.o4Xy91eU9YnOJ/zhPhEE8hqXP9O1/kgqJv3I4S",
                            Role = "Student",
                            UserName = "student2"
                        });
                });

            modelBuilder.Entity("School_Project_API.Entities.Attendance", b =>
                {
                    b.HasOne("School_Project_API.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("School_Project_API.Entities.Class", b =>
                {
                    b.HasOne("School_Project_API.Entities.Teacher", "Teacher")
                        .WithMany("Class")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("School_Project_API.Entities.Homework", b =>
                {
                    b.HasOne("School_Project_API.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("School_Project_API.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("School_Project_API.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("School_Project_API.Entities.Student", b =>
                {
                    b.HasOne("School_Project_API.Entities.AccessCard", "AccessCard")
                        .WithOne("Student")
                        .HasForeignKey("School_Project_API.Entities.Student", "CardId");

                    b.HasOne("School_Project_API.Entities.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("AccessCard");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("School_Project_API.Entities.StudentSubjects", b =>
                {
                    b.HasOne("School_Project_API.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Project_API.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("School_Project_API.Entities.Subject", b =>
                {
                    b.HasOne("School_Project_API.Entities.Course", "Course")
                        .WithMany("Subject")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School_Project_API.Entities.Teacher", "Teacher")
                        .WithMany("Subject")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("School_Project_API.Entities.Teacher", b =>
                {
                    b.HasOne("School_Project_API.Entities.Department", "Department")
                        .WithMany("Teachers")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("School_Project_API.Entities.AccessCard", b =>
                {
                    b.Navigation("Student")
                        .IsRequired();
                });

            modelBuilder.Entity("School_Project_API.Entities.Course", b =>
                {
                    b.Navigation("Subject");
                });

            modelBuilder.Entity("School_Project_API.Entities.Department", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("School_Project_API.Entities.Teacher", b =>
                {
                    b.Navigation("Class");

                    b.Navigation("Subject");
                });
#pragma warning restore 612, 618
        }
    }
}
